### ISSUE TITLE
Add a way to close dialers and instance refreshs

### ISSUE THREAD

**Issue by kurtisvg** [kurtisvg/cloud-sql-go-connector#5]
Right now, once an instance is dialer, it will continue to refresh those certificates indefinitely. We should expose some way to close the DialManager in a way that propagates down to the instance objects and stops refreshes:

https://github.com/kurtisvg/cloud-sql-go-connector/blob/7e8955216cc91999e3d8d17ed9eced8f63564ca7/internal/cloudsql/instance.go#L100-L114

**Comment by kurtisvg** [comment]
I think there are 3-ish reasonable ways to do this:

1. Have the user's hand in a context to `NewDialer`, which they can attach their own cancel func to.

2. Have `NewDialer` return a cancel func, which closes the instance

3. Add a `Close` method that cancel's the context(s) all the way down

**Comment by enocom** [comment]
I vote for option 3. It feels the most idiomatic.

Looking at the uses of context in `NewDialer`, I see only `sqladmin.NewService` accepts a context. And in any case, wherever we use the `sqladmin.Service`, there's an associated `Context` function that we're using. So we can possibly drop context as an argument from `NewDialer`.

Meanwhile as for implementation details for option 3, we could thread the context from `Dial` down into `d.instance`, so a client could cancel the refresh with a timeout for instance. And it still makes sense to have a `Close` function in addition, such that a client can turn off the dialer when they're done with it, separately from whatever uses of context there might be.

**Comment by kurtisvg** [comment]
> Looking at the uses of context in `NewDialer`, I see only `sqladmin.NewService` accepts a context. And in any case, wherever we use the `sqladmin.Service`, there's an associated `Context` function that we're using. So we can possibly drop context as an argument from `NewDialer`.

The context for NewService (and thus NewDialer) is used for network calls made during startup, not as the default context for all requests. So there are 3 distinct kinds of "contexts" - a startup context, a refresh context, and a dial context.

The proposed `Close` method would only cancel the "refresh" context to prevent future refreshes.

**Comment by enocom** [comment]
In that case, [this line](https://github.com/kurtisvg/cloud-sql-go-connector/blob/18c58a19cfb0a5659fc09a477644770e98bcb45c/dialer.go#L96) should use probably use the context provided to `NewDialer`.
